import { CardAtlas } from "./CardAtlas";

export type AtlasData<T extends string = string> = {
  textureUrl: string;
  cardWidth: number;
  cardHeight: number;
  hGap: number;
  vGap: number;
  lookup: readonly T[];
  excluded: T[];
};

const atlantisLookupArray = [
  "CUPS_ACE",
  "CUPS_2",
  "CUPS_3",
  "CUPS_4",
  "CUPS_5",
  "CUPS_6",
  "CUPS_7",
  "CUPS_8",
  "CUPS_9",
  "CUPS_10",
  "CUPS_KNIGHT",
  "CUPS_KNAVE",
  "CUPS_QUEEN",
  "CUPS_KING",
  "PENTACLES_ACE",
  "PENTACLES_2",
  "PENTACLES_3",
  "PENTACLES_4",
  "PENTACLES_5",
  "PENTACLES_6",
  "PENTACLES_7",
  "PENTACLES_8",
  "PENTACLES_9",
  "PENTACLES_10",
  "PENTACLES_KNIGHT",
  "PENTACLES_KNAVE",
  "PENTACLES_QUEEN",
  "PENTACLES_KING",
  "SWORDS_ACE",
  "SWORDS_2",
  "SWORDS_3",
  "SWORDS_4",
  "SWORDS_5",
  "SWORDS_6",
  "SWORDS_7",
  "SWORDS_8",
  "SWORDS_9",
  "SWORDS_10",
  "SWORDS_KNIGHT",
  "SWORDS_KNAVE",
  "SWORDS_QUEEN",
  "SWORDS_KING",
  "WANDS_ACE",
  "WANDS_2",
  "WANDS_3",
  "WANDS_4",
  "WANDS_5",
  "WANDS_6",
  "WANDS_7",
  "WANDS_8",
  "WANDS_9",
  "WANDS_10",
  "WANDS_KNIGHT",
  "WANDS_KNAVE",
  "WANDS_QUEEN",
  "WANDS_KING",
  "FOOL_0",
  "MAGICIAN_1",
  "HIGH_PRIESTESS_2",
  "EMPRESS_3",
  "EMPEROR_4",
  "HIEROPHANT_5",
  "LOVERS_6",
  "CHARIOT_7",
  "STRENGTH_11",
  "HERMIT_9",
  "WHEEL_OF_FORTUNE_10",
  "JUSTICE_8",
  "HANGED_MAN_12",
  "DEATH_13",
  "TEMPERANCE_14",
  "DEVIL_15",
  "TOWER_16",
  "STAR_17",
  "MOON_18",
  "SUN_19",
  "JUDGEMENT_20",
  "WORLD_21",
  "BACK",
] as const;

type AtlantisCardOptions = (typeof atlantisLookupArray)[number];

const atlantisData: AtlasData<AtlantisCardOptions> = {
  textureUrl: "Atlantis.jpg",
  cardWidth: 345,
  cardHeight: 642,
  hGap: 8,
  vGap: 7,
  lookup: atlantisLookupArray,
  excluded: ["BACK"],
};

const animalLookupArray = [
  "CUPS_ACE",
  "CUPS_2",
  "CUPS_3",
  "CUPS_4",
  "CUPS_5",
  "CUPS_6",
  "CUPS_7",
  "CUPS_8",
  "CUPS_9",
  "CUPS_10",
  "CUPS_KNIGHT",
  "CUPS_KNAVE",
  "CUPS_QUEEN",
  "CUPS_KING",
  "PENTACLES_ACE",
  "PENTACLES_2",
  "PENTACLES_3",
  "PENTACLES_4",
  "PENTACLES_5",
  "PENTACLES_6",
  "PENTACLES_7",
  "PENTACLES_8",
  "PENTACLES_9",
  "PENTACLES_10",
  "PENTACLES_KNIGHT",
  "PENTACLES_KNAVE",
  "PENTACLES_QUEEN",
  "PENTACLES_KING",
  "SWORDS_ACE",
  "SWORDS_2",
  "SWORDS_3",
  "SWORDS_4",
  "SWORDS_5",
  "SWORDS_6",
  "SWORDS_7",
  "SWORDS_8",
  "SWORDS_9",
  "SWORDS_10",
  "SWORDS_KNIGHT",
  "SWORDS_KNAVE",
  "SWORDS_QUEEN",
  "SWORDS_KING",
  "WANDS_ACE",
  "WANDS_2",
  "WANDS_3",
  "WANDS_4",
  "WANDS_5",
  "WANDS_6",
  "WANDS_7",
  "WANDS_8",
  "WANDS_9",
  "WANDS_10",
  "WANDS_KNIGHT",
  "WANDS_KNAVE",
  "WANDS_QUEEN",
  "WANDS_KING",
  "FOOL_0",
  "MAGICIAN_1",
  "HIGH_PRIESTESS_2",
  "EMPRESS_3",
  "EMPEROR_4",
  "HIEROPHANT_5",
  "LOVERS_6",
  "CHARIOT_7",
  "STRENGTH_11",
  "HERMIT_9",
  "WHEEL_OF_FORTUNE_10",
  "JUSTICE_8",
  "HANGED_MAN_12",
  "DEATH_13",
  "TEMPERANCE_14",
  "DEVIL_15",
  "TOWER_16",
  "STAR_17",
  "MOON_18",
  "SUN_19",
  "JUDGEMENT_20",
  "WORLD_21",
  "COVER",
  "EXTRA",
  "BACK",
] as const;

type AnimalCardOptions = (typeof animalLookupArray)[number];

const animalData: AtlasData<AnimalCardOptions> = {
  textureUrl: "Animal_Lords.jpg",
  cardWidth: 336,
  cardHeight: 600,
  hGap: 8,
  vGap: 8,
  lookup: animalLookupArray,
  excluded: ["BACK", "COVER", "EXTRA"],
};

const playingCardsLookupArray = [
  "SPADES_ACE",
  "SPADES_2",
  "SPADES_3",
  "SPADES_4",
  "SPADES_5",
  "SPADES_6",
  "SPADES_7",
  "SPADES_8",
  "SPADES_9",
  "SPADES_10",
  "SPADES_JACK",
  "SPADES_QUEEN",
  "SPADES_KING",
  "HEARTS_ACE",
  "HEARTS_2",
  "HEARTS_3",
  "HEARTS_4",
  "HEARTS_5",
  "HEARTS_6",
  "HEARTS_7",
  "HEARTS_8",
  "HEARTS_9",
  "HEARTS_10",
  "HEARTS_JACK",
  "HEARTS_QUEEN",
  "HEARTS_KING",
  "DIAMONDS_ACE",
  "DIAMONDS_2",
  "DIAMONDS_3",
  "DIAMONDS_4",
  "DIAMONDS_5",
  "DIAMONDS_6",
  "DIAMONDS_7",
  "DIAMONDS_8",
  "DIAMONDS_9",
  "DIAMONDS_10",
  "DIAMONDS_JACK",
  "DIAMONDS_QUEEN",
  "DIAMONDS_KING",
  "CLUBS_ACE",
  "CLUBS_2",
  "CLUBS_3",
  "CLUBS_4",
  "CLUBS_5",
  "CLUBS_6",
  "CLUBS_7",
  "CLUBS_8",
  "CLUBS_9",
  "CLUBS_10",
  "CLUBS_JACK",
  "CLUBS_QUEEN",
  "CLUBS_KING",
  "JOKER_RED",
  "JOKER_BLACK",
  "BACK",
] as const;
type PlayingCardOptions = (typeof playingCardsLookupArray)[number];

const playingCardData: AtlasData<PlayingCardOptions> = {
  textureUrl: "Playing_Cards.png",
  cardWidth: 352,
  cardHeight: 537,
  hGap: 5.5,
  vGap: 0,
  lookup: playingCardsLookupArray,
  excluded: ["BACK"],
};

const macMahonLookupArray = [
  "1111",
  "1112",
  "1113",
  "1122",
  "1212",
  "1132",
  "1123",
  "1213",
  "1133",
  "1313",
  "2122",
  "2132",
  "2123",
  "3122",
  "2133",
  "3132",
  "3123",
  "3133",
  "2222",
  "2223",
  "2233",
  "2323",
  "3233",
  "3333",
] as const;
type MacMahonOptions = (typeof macMahonLookupArray)[number];

const macMahonData: AtlasData<MacMahonOptions> = {
  textureUrl: "MacMahon.png",
  cardWidth: 386,
  cardHeight: 386,
  hGap: 48,
  vGap: 48,
  lookup: macMahonLookupArray,
  excluded: [],
};

const atlantisTarotAtlas = new CardAtlas(atlantisData);
await atlantisTarotAtlas.load();

const animalTarotAtlas = new CardAtlas(animalData);
await animalTarotAtlas.load();

const playingCardAtlas = new CardAtlas(playingCardData);
await playingCardAtlas.load();

const macMahonAtlas = new CardAtlas(macMahonData);
await macMahonAtlas.load();

(playingCardAtlas.excluded as string[]).push("JOKER_RED", "JOKER_BLACK");

export {
  atlantisTarotAtlas,
  animalTarotAtlas,
  playingCardAtlas,
  macMahonAtlas,
};
